---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: daily
      #time: "15:00"
      #timezone: "Europe/London"
    target-branch: "dependabot-patch-npm"
    open-pull-requests-limit: 6
