version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: daily
      # time: "15:27"
      # timezone: "Europe/London"
    open-pull-requests-limit: 6
    labels:
      - "javascript"
