name: Publish to NPM

on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies 🔧
        run: npm --prefix $PR_PATH ci
        env:
          PR_PATH: ${{steps.dependabot-metadata.outputs.description}}
      # - name: Run Build 🔧
      #   run: npm --prefix javascript/ run build
