name: Publish to NPM

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies 🔧
        if: contains(github.event.pull_request.labels.*.name, 'javascript')
        run: npm --prefix javascript ci
