name: Publish to NPM

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies 🔧
        run: npm --prefix $PR_PATH ci
        env:
          PR_PATH: ${{github.event.pull_request.labels.description}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: Run Build 🔧
      #   run: npm --prefix javascript/ run build
